version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "1433:1433"
    environment:
        - SA_PASSWORD=${SA_PASSWORD}
        - ACCEPT_EULA=Y        
    volumes:
      - ./scripts:/scripts
      - ./ci/logs:/ci/logs
    healthcheck:
      test: ["CMD", "${SQL_CMD}", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "select 1"] 
      timeout: 1s
      retries: 10